### ISSUE TITLE
do you know how to get the IP address of the NGIMU?

### ISSUE THREAD

**Issue by chlee0216** [xioTechnologies/NGIMU-Python-Example#2]
What should I do in order to get the IP address of the NGIMU on Linux (Ubuntu 16.04)? I tried to find the answer using the manual and the example code, but no good result came. Please help.

**Comment by xioTechnologies** [comment]
The NGIMU's IP address in AP mode is 192.168.1.1.  In Client mode and with DHCP enabled, the NGIMU's IP address will be assigned by the Wi-Fi router.  You can always view the NGIMU's IP address in the NGIMUs settings using the NGIMU GUI.

**Comment by chlee0216** [comment]
So how should I run GUI? I see the folder NGIMU GUI, but you don't have any detailed instructions as to how to run it

**Comment by xioTechnologies** [comment]
It is a Windows application.  Double click it to run it.

**Comment by chlee0216** [comment]
this means I cannot run this on Linux, right?

**Comment by xioTechnologies** [comment]
The NGIMU is a Windows application.  It only runs on Windows.

**Comment by chlee0216** [comment]
So then do you mean that the python and C++ code examples can run only on Windows as well?

**Comment by xioTechnologies** [comment]
No.  C++ and Python are programming languages, they are not associated with any OS.

**Comment by chlee0216** [comment]
so if I need to use the Python example in Linux, I first have to get the IP address of the device using the Windows GUI application, get the IP address, and use it in the python code. Am I right?

**Comment by chlee0216** [comment]
or is there any way for the device to send data to the connected machine via USB instead of using Wifi?

**Comment by xioTechnologies** [comment]
You can get the IP address in a number of ways.  In AP mode it is fixed at 192.168.1.1.  In Client mode the IP address will be visible in your router 'connected devices' information.  The Python script modifies the NGIMU's send IP address to match that of your computer.

The NGIMU send data via: USB, serial and Wi-Fi.  This Python example only sues Wi-Fi.

**Comment by chlee0216** [comment]
Ok. Thanks for your detailed explanation. Do you then have any sample code in either language that would utilize USB connection for data exchange? or is there any reference I can look up to?
Please understand if I seem to rely upon your help, but I am new to the IMU and embedded development in general, so I do need some advice on this.

**Comment by xioTechnologies** [comment]
This discussion is no longer relevant to the Python example.  Please continue the discussion with customer support.
