### ISSUE TITLE
pyosc support  discontinued

### ISSUE THREAD

**Issue by swethasharma** [xioTechnologies/NGIMU-Python-Example#3]
I tried the code with pyosc but i was not able to fix some issue with dependent library. I had to install python osc and python3.  I want to connect to the sensor for a time period of 10 minutes and terminate the connection. The following is the code I have:

from pythonosc import udp_client
from pythonosc import osc_message_builder
from pythonosc import dispatcher
import socket, threading, time
from pythonosc import osc_server
import time

tstart=time.time();
# Change this to the NGIMU IP address
send_address = '192.100.1.1', 9000

client =udp_client.SimpleUDPClient('192.100.1.1', 9000)

# msg=osc_message_builder.OscMessageBuilder()
# msg=msg.build()
print(str(socket.gethostbyname(socket.gethostname())))

#receive_address='192.100.16.2', 8000
dispatcher = dispatcher.Dispatcher()

server = osc_server.ThreadingOSCUDPServer(('192.100.16.2', 8001),dispatcher)
#server.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
print("Serving on {}".format(server.server_address))

server.server_activate()
#server.server_close()

tnow= time.time();
tdiff= tnow-tstart
while(tdiff*1000<10):
    tnow= time.time();
    tdiff= tnow-tstart;
    print(tdiff)
    if(tdiff*1000>10):
       server.server_close()`

It gives me an error:

File "C:/sensor/ngimu.py", line 27, in server = osc_server.ThreadingOSCUDPServer(('192.168.1.2', 8001),dispatcher)

File "C:\ProgramData\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 107, in init super().init(server_address, _UDPHandler)

File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 453, in init self.server_bind()

File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 467, in server_bind self.socket.bind(self.server_address)

OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

Can you post a code with python3 and pythonosc?

**Comment by xioTechnologies** [comment]
The example no longer uses pyosc

**Comment by twisharaja** [comment]
Hi Shweta, did you find the solution to your question?
