### ISSUE TITLE
Where is the client storing the timetag

### ISSUE THREAD

**Issue by nchollan** [xioTechnologies/NGIMU-Python-Example#4]
I am using an ngimu, and trying to read the timestamps from the incoming OSC packets using python-osc. Is there any example of how I should approach retrieving these timetags? (I would also like to set the time on the ngimu, I was unsuccessful sending a '/time' message)

**Comment by xioTechnologies** [comment]
The /time message should have a single OSC-Timetag argument.  This will set the date and time of the NGIMU.  Measurement messages sent by the NGIMU are in OSC bundles.  The timetag of each OSC bundle is the timestamp of the measurement.
