### ISSUE TITLE
How do I get sensor to send name?

### ISSUE THREAD

**Issue by totuni** [xioTechnologies/NGIMU-Python-Example#6]
I have added this the the python sample.   dispatcher.map("/name", name)
However, the device never sends this info. So my python script doesn't know which sensor is sending in data.  If I have 2 sensors sending to the same osc server the name needs to be included on all data or there is no way to know which one is sending in what.   From the NGIMU gui you can issue a read from device command but  don't know how to make this happen from the python script.  suggestions?

**Comment by xioTechnologies** [comment]
The example now support multiple NGIMUs.
