### ISSUE TITLE
udp port and ip in python example

### ISSUE THREAD

**Issue by ep8472** [xioTechnologies/NGIMU-Python-Example#7]
The comment in script.py says that udp_ports must be an array of ports listen to and "These ports must be equal to
 the UDP Send Port in the NGIMU settings." I checked with the GUI, the UDP send port is 8000, so changed to:

udp_ports = [8000]

For ip, the comment says "The UDP Send IP Address setting must be the computer's IP address". But it's not working with my ip address...

The next sentence is unclear: "Both these settings are changed automatically when connecting to the NGIMU using the NGIMU GUI." So what am I required to do? Running the GUI, checking udp send port and ip, closing GUI and starting the python example? Can you give me an advice/clarification what to do?

Hint/Info: With the GUI I can connect to the device, but only via serial (Comport). When cklicking on UDP, I get an error. I would actually like to read the device over USB from a python script.

**Comment by xioTechnologies** [comment]
I suggest you use do the following:
1. Use the NGIMU GUI to establish a UDP connection
2. Read the device settings using the NGIMU GUI and make a note of the UDP port
3. Close the NGIMU GUI
4. Edit the UDP port in the script
5. Run the script

The Python scrip is for UDP only, not USB.

**Comment by ep8472** [comment]
Thanks, but as mentioned I get an error when establishing a UDP connection via GUI. After cklicking on "UDP Wi-Fi" I got a lot of output like ".../battery/cycles" on the console and then it stops with th error message "Could not read all settings".

So I have either to fix this, or (preferred) is it possible to read the NGIMU over USB using Python? E.g. by pyserial?

**Comment by xioTechnologies** [comment]
We do not have a Python example for communicating with the NGIMU via serial.  It should be straight-forward to create if you wanted to give it a go.  You would need to process the received byte stream through a SLIP decoder* to break up the stream into separate packets, and then process each packet using the `decode` function in this example.

*SLIP decoder links:

- https://en.wikipedia.org/wiki/Serial_Line_Internet_Protocol
- https://github.com/xioTechnologies/OSC99/blob/master/Osc99/OscSlip.c#L119

You should be able to use the NGIMU GUI without issues.  Perhaps you are opening a manually configured connection rather than using the Search For Connection feature.  I suggest you use the Search For Connection feature to avoid errors.  If you are still unable to connect then the issue will be due to a firewall or security settings on your machine.

**Comment by ep8472** [comment]
I tried and got this code working to read data from NGIMU via serial:

`import serial
import osc_decoder
import ntplib
from datetime import datetime, timezone

// I checked all my comports and found that NGIMU is on COM7

s = serial.Serial('COM7', baudrate=115200)
res = s.read(100)
res2 = osc_decoder.decode(res)
print(res2)
ntptime = res2[0][0]
ts = ntplib.ntp_to_system_time(ntptime)
print("Time stamp: ", datetime.fromtimestamp(ts))
`
The output is:
[[3840080422.130429, '/sensors', -0.0948677510023117, 0.044160131365060806, -0.010756969451904297, -0.021548423916101456, -0.021106990054249763, 0.9926797151565552, 7.986533164978027, 16.790851593017578, -57.42274475097656, 1020.9420776367188]]
Time stamp:  2021-09-08 11:00:22.130429

So obviously the first number is the time (as described in your manual), and the next numbers are gyrometer etc. until the last number looks like the pressure in hPa (which is also in agreement with the manual).

I basically have 3 questions:

1. I'm reading arbitrarily 100 Bytes. I do that because 10 Bytes were giving an error, and 1000 Bytes didn't provide a longer decoded message. For decoding I imported osc_decoding from your Python UDP example. Is that ok, or do I need to loop over reading Bytes until encountering any Stop-Byte (I'm not sure because you explicitly mentioned the SLIP decoder in your last comment)? Is there a typical length of the message in Bytes?
2. How to write to the NGIMU and do I need to encode data then?
3. I'm actually interested in roll and pitch angles in degrees. How do I get them (above I only get accelertion in g etc...)

**Comment by xioTechnologies** [comment]
1. Your code is only partially working.  Many packets are being lost because you are not decoding the data correctly.  You need to turn the incoming byte stream into packets.  This is done by decoding as per the SLIP protocol.  The length of a packet varies with the content as per the SLIP protocol.
2. You write to the NGIMU by encoding an OSC message as a SLIP packet and sending that.
3. If you want Euler Angles messages then you need to set the Euler Angles send rate to a non-zero value in the device settings (e.g. 50 Hz).  I suggest you disable all messages (i.e. set send rate to 0 Hz) that you are not interested in.

**Comment by ep8472** [comment]
So reading a fixed amount of bytes and using osc_decoder from your UDP example is not working? Because in that example you use
`data, addr = udp_socket.recvfrom(2048)`
so I guess this is reading 2048 bytes(?) followed by
`osc_decoder.decode(data)`

Instead, I need to read Byte-by-Byte and merge the decoding functions from here 
https://github.com/xioTechnologies/OSC99/blob/master/Osc99/OscSlip.c#L119
into my code? 

One addtional question: For the serial connection, do I need any to define any parity or stopbits etc., e.g.
`serial.PARITY_NONE
serial.STOPBITS_ONE`

Will give it a try!

**Comment by xioTechnologies** [comment]
UDP sends data as packets.  Serial/USB sends data as a stream.  Data received by UDP can be immediately be processed as OSC packets.  Data received by serial/USB must be first decoded using SLIP to obtain the OSC packets.  `udp_socket.recvfrom(2048)` gets the latest packet and the value 2048 is an arbitrarily high value to ensure that the complete packet is read.

If you are receiving by serial then you need to process byte-by-byte as per the OSC99 SLIP decoder linked above.  The serial settings should have no effect for USB serial emulation.  I suggest you use default values.

**Comment by ep8472** [comment]
Thanks, I understand! The OSC99 SLIP decoder that you linked above is in C++. Do you have a complete C++ example project how to read and write to NGIMU using serial/USB? Then I would just switch to C++, it's presmably easier than translating C++ functions to Python. (For me C++ is as good as Python anyways...).

**Comment by xioTechnologies** [comment]
Here is a complete C++ example:
https://github.com/xioTechnologies/NGIMU-C-Cpp-Example

**Comment by ep8472** [comment]
Many thanks! Meanwhile I also managed to retrieve OSC packets from serial/USB stream and then used your osc_decoder library provided with the UDP example. If this is of interest for someone I provided the Python code below (showing only humidty and temperature messages).

Question: There are no "/euler" messages coming in, which are of high interest as being roll and pitch and yaw angles in degrees. Do I need to switch them on somewhere?

```
import serial
import osc_decoder
import ntplib
from datetime import datetime, timezone
import keyboard

s = serial.Serial('COM7', baudrate=115200)
while True:
    if keyboard.is_pressed("q"):
        print("q pressed, eqqqnding loop")
        break

    i=0
    while True:
         res = s.read(1)
         #print(res)
         
         if res == b'\xC0':                 # SLIP_END --> break
             #print("SLIP end")
             break
         else:
            
             if res == b'\xDB':             # SLIP_ESC
                res_next = s.read(1)        # read next
                if res_next == b'\xDC':     # SLIP_ESC_END
                    res = b'\xC0'           # SLIP_END
                elif res_next == b'\xDD':   # SLIP_ESC_ESC
                    res = b'\xDB'           # SLIP_ESC
            
             if i == 0:
                  data = res
             else:
                 data = data + res
             i = i + 1

    if i != 0:
        #print(data)
        #print("length = ", i)

        res2 = osc_decoder.decode(data)[0]
        
        # Show only Humidity messages
        if (res2[1] == '/humidity'):    
            print(res2)
        
        # Show only Temperature messages
        if (res2[1] == '/temperature'):    
            print(res2)
        
        # Show only Roll and Pitch messages
        if (res2[1] == '/euler'):    
            print(res2)
   ```

**Comment by ep8472** [comment]
Hi, after reading and decoding works now, I try to write to the NGIMU via serial. Just tried to send "/identify" (because then LEDs would start to blink, it's easy to see...).

According to OSC specification, the length of the message needs to be a multiple of four and NULL-terminated. "/identify" has 9 characters, so I added 3 \x00. For SLIP I also added a \xc0 (SLIP_END).

So in total:
s = serial.Serial('COM7', baudrate=115200)
my_str = '/identify'
my_str_as_bytes = str.encode(my_str)
my_str_as_bytes = my_str_as_bytes + b'\x00' + b'\x00' + b'\x00' + b'\xC0'
s.write(my_str_as_bytes)

However, LEDs don't start to blink and as an answer I get the error:
b'/error\x00\x00,s\x00\x00Source data ends before the start of type tag string.\x00\x00\x00'

What is my mistake?

**Comment by xioTechnologies** [comment]
If you want the NGIMU to send Euler angle messages then you need to set the Euler angle send rate to a non-zero value in the device settings.

The OSC message you have constructed does not include a type-tag string.  The complete OSC message encoded as a SLIP packet would be `"/identify\0\0\0,\0\0\0\xC0"`.

**Comment by ep8472** [comment]
Both works now, many thanks, you helped a lot!

Before closing the issue: I have one last non-programmatical question (maybe you can help on that as well). My NGIMU has a plastic housing and came with a battery. Does it need the battery when connected via USB?
The point is, I noticed that it gets quite warm when running, which affects the humidity measurement. It starts around 50%, which is realistic (my weather station shows the same), but gets down to 10% when the sensor is running and warming... So I thought about removing the plastic housing and maybe also the battery (producing heat when charging...)? I only intend to use the NGIMU on a USB cable, so that's fine for me.

And by the way: Is the USB a USB3? The cable is quite short, so I used a longer one (rather old cable), which didn't work.

**Comment by xioTechnologies** [comment]
The NGIMU does not need a battery connected.

**Comment by samanzr** [comment]
Hi everyone,

Thank you to send us your code...

> Many thanks! Meanwhile I also managed to retrieve OSC packets from serial/USB stream and then used your osc_decoder library provided with the UDP example. If this is of interest for someone I provided the Python code below (showing only humidty and temperature messages).
> 
> Question: There are no "/euler" messages coming in, which are of high interest as being roll and pitch and yaw angles in degrees. Do I need to switch them on somewhere?
> 
> ```
> import serial
> import osc_decoder
> import ntplib
> from datetime import datetime, timezone
> import keyboard
> 
> s = serial.Serial('COM7', baudrate=115200)
> while True:
>     if keyboard.is_pressed("q"):
>         print("q pressed, eqqqnding loop")
>         break
> 
>     i=0
>     while True:
>          res = s.read(1)
>          #print(res)
>          
>          if res == b'\xC0':                 # SLIP_END --> break
>              #print("SLIP end")
>              break
>          else:
>             
>              if res == b'\xDB':             # SLIP_ESC
>                 res_next = s.read(1)        # read next
>                 if res_next == b'\xDC':     # SLIP_ESC_END
>                     res = b'\xC0'           # SLIP_END
>                 elif res_next == b'\xDD':   # SLIP_ESC_ESC
>                     res = b'\xDB'           # SLIP_ESC
>             
>              if i == 0:
>                   data = res
>              else:
>                  data = data + res
>              i = i + 1
> 
>     if i != 0:
>         #print(data)
>         #print("length = ", i)
> 
>         res2 = osc_decoder.decode(data)[0]
>         
>         # Show only Humidity messages
>         if (res2[1] == '/humidity'):    
>             print(res2)
>         
>         # Show only Temperature messages
>         if (res2[1] == '/temperature'):    
>             print(res2)
>         
>         # Show only Roll and Pitch messages
>         if (res2[1] == '/euler'):    
>             print(res2)
> ```

I have got this error:
osc_decoder.decode(data)[0]
IndexError: list index out of range

Could you please help me?
(Hint: I am using the raspberry pi 4 model B to read data from NGIMU through USB port)

**Comment by ep8472** [comment]
Hi samanzr,

I had the same issue and figured out that this happens if a message (data) does not start with "#" (Ascii code 35), which happens somethimes for some reason... I moved everything in an if-condition, so try the following:
```
if data[0] == 35:
    osc_decoder.decode(data)[0]
    # and so on...
```

**Comment by samanzr** [comment]
> ep8472

Thank you for sharing your solution. It is working now.
