### ISSUE TITLE
Python example in BeagleBone Blue

### ISSUE THREAD

**Issue by elenabardi** [xioTechnologies/NGIMU-Python-Example#8]
Hello, 

I am trying to read NGIMUs data via UDP on a BeagleBone using the example you provided. I inserted the port numbers indicated by the GUI and it worked once. After that, it never worked anymore. The error I get is: [Errno 11] Resource temporarily unavailable 

Is it possible that the port numbers are different from the ones displayed in the GUI? Do you have any suggestions on how to solve this issue? 

Thank you!
Elena

**Comment by xioTechnologies** [comment]
You need to configure the NGIMU to send to the IP address of your BeagleBone, using the port that your BeagleBone is listening to.  The _UDP Send IP Address_ and _UDP Send Port_ are settings in the NGIMU.  I suggest you connect to the NGIMU using the GUI and a USB connection and use this connection to find the right UDP settings.  The NGIMU can be simultaneously connected to one device via USB and another via UDP.

**Comment by elenabardi** [comment]
It works perfectly, thank you very much for the support.

Elena
